package Admin;

/**
 *
 * @author Muhammed (BE) / Kesara (FE)
 */

import classes.AdminUserAdd;
import javax.swing.JOptionPane;

public class AddEditUsers extends javax.swing.JFrame {

    /**
     * Creates new form UserSettings
     */
    public AddEditUsers() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
          // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
          private void initComponents() {

                    jUpdateButton = new javax.swing.JButton();
                    jDeleteButtton = new javax.swing.JButton();
                    jTypeAdmin = new javax.swing.JComboBox<>();
                    jLabel6 = new javax.swing.JLabel();
                    jConfirmPassAdmin = new javax.swing.JPasswordField();
                    jLabel5 = new javax.swing.JLabel();
                    jPasswordAdmin = new javax.swing.JPasswordField();
                    jLabel4 = new javax.swing.JLabel();
                    jNameAdmin = new javax.swing.JTextField();
                    jLabel3 = new javax.swing.JLabel();
                    jAddButton = new javax.swing.JButton();
                    jButton1 = new javax.swing.JButton();
                    jLabel2 = new javax.swing.JLabel();
                    jLabel1 = new javax.swing.JLabel();

                    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
                    setBackground(new java.awt.Color(255, 255, 255));
                    setMinimumSize(new java.awt.Dimension(450, 650));
                    setResizable(false);
                    setSize(new java.awt.Dimension(450, 650));
                    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                    jUpdateButton.setBackground(new java.awt.Color(38, 106, 169));
                    jUpdateButton.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
                    jUpdateButton.setForeground(new java.awt.Color(255, 255, 255));
                    jUpdateButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/update.png"))); // NOI18N
                    jUpdateButton.setText("Update");
                    jUpdateButton.setAlignmentY(0.0F);
                    jUpdateButton.setBorder(null);
                    jUpdateButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
                    jUpdateButton.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        jUpdateButtonActionPerformed(evt);
                              }
                    });
                    getContentPane().add(jUpdateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 110, 40));

                    jDeleteButtton.setBackground(new java.awt.Color(38, 106, 169));
                    jDeleteButtton.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
                    jDeleteButtton.setForeground(new java.awt.Color(255, 255, 255));
                    jDeleteButtton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
                    jDeleteButtton.setText("Delete");
                    jDeleteButtton.setAlignmentY(0.0F);
                    jDeleteButtton.setBorder(null);
                    jDeleteButtton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
                    jDeleteButtton.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        jDeleteButttonActionPerformed(evt);
                              }
                    });
                    getContentPane().add(jDeleteButtton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 520, 110, 40));

                    jTypeAdmin.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
                    jTypeAdmin.setForeground(new java.awt.Color(64, 134, 200));
                    jTypeAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Faculty Staff", "Member" }));
                    jTypeAdmin.setBorder(null);
                    getContentPane().add(jTypeAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, 140, 30));

                    jLabel6.setBackground(new java.awt.Color(255, 255, 255));
                    jLabel6.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
                    jLabel6.setForeground(new java.awt.Color(255, 255, 255));
                    jLabel6.setText("User Type ");
                    getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 190, 20));

                    jConfirmPassAdmin.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
                    jConfirmPassAdmin.setForeground(new java.awt.Color(64, 134, 200));
                    jConfirmPassAdmin.setBorder(null);
                    getContentPane().add(jConfirmPassAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 140, 30));

                    jLabel5.setBackground(new java.awt.Color(255, 255, 255));
                    jLabel5.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
                    jLabel5.setForeground(new java.awt.Color(255, 255, 255));
                    jLabel5.setText("Confirm Password");
                    getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 200, 20));

                    jPasswordAdmin.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
                    jPasswordAdmin.setForeground(new java.awt.Color(64, 134, 200));
                    jPasswordAdmin.setBorder(null);
                    getContentPane().add(jPasswordAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 180, 140, 30));

                    jLabel4.setBackground(new java.awt.Color(255, 255, 255));
                    jLabel4.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
                    jLabel4.setForeground(new java.awt.Color(255, 255, 255));
                    jLabel4.setText("Password  ");
                    getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, 190, 20));

                    jNameAdmin.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
                    jNameAdmin.setForeground(new java.awt.Color(64, 134, 200));
                    jNameAdmin.setBorder(null);
                    getContentPane().add(jNameAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 140, 30));

                    jLabel3.setBackground(new java.awt.Color(255, 255, 255));
                    jLabel3.setFont(new java.awt.Font("Poppins SemiBold", 0, 18)); // NOI18N
                    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                    jLabel3.setText("Username ");
                    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 180, 20));

                    jAddButton.setBackground(new java.awt.Color(38, 106, 169));
                    jAddButton.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
                    jAddButton.setForeground(new java.awt.Color(255, 255, 255));
                    jAddButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add.png"))); // NOI18N
                    jAddButton.setText("Add");
                    jAddButton.setAlignmentY(0.0F);
                    jAddButton.setBorder(null);
                    jAddButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
                    jAddButton.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        jAddButtonActionPerformed(evt);
                              }
                    });
                    getContentPane().add(jAddButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 520, 80, 40));

                    jButton1.setBackground(new java.awt.Color(237, 30, 121));
                    jButton1.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
                    jButton1.setForeground(new java.awt.Color(255, 255, 255));
                    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
                    jButton1.setText("Back");
                    jButton1.setAlignmentY(0.0F);
                    jButton1.setBorder(null);
                    jButton1.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        jButton1ActionPerformed(evt);
                              }
                    });
                    getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 80, 40));

                    jLabel2.setBackground(new java.awt.Color(237, 30, 121));
                    jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 30)); // NOI18N
                    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                    jLabel2.setText("Add/Edit Users");
                    jLabel2.setAlignmentY(0.0F);
                    jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 230, 60));

                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg-08.png"))); // NOI18N
                    jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
                    jLabel1.setMaximumSize(new java.awt.Dimension(450, 650));
                    jLabel1.setMinimumSize(new java.awt.Dimension(450, 650));
                    jLabel1.setPreferredSize(new java.awt.Dimension(450, 650));
                    getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 670));

                    pack();
          }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.toBack();
        setVisible(false);
        new UserSettings().toFront();
        new UserSettings().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jUpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUpdateButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jUpdateButtonActionPerformed

          private void jAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jAddButtonActionPerformed
                    // TODO add your handling code here:
                    
                    String usernaeme = jNameAdmin.getText();
                    String password = jPasswordAdmin.getText();
                    String type = jTypeAdmin.getToolTipText();
                    String passwordConfirm = jConfirmPassAdmin.getText();
                    
                    AdminUserAdd obj = new AdminUserAdd();
                    boolean value = obj.addUser(usernaeme, password, type, passwordConfirm);
                    
                    if ( value ){
                              System.out.println("Successfully added the user!!");
                    }
                    else {
                              System.out.println("Eror in adding user!!"); 
                    }
          }//GEN-LAST:event_jAddButtonActionPerformed

          private void jDeleteButttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDeleteButttonActionPerformed
                    // TODO add your handling code here:
                    
                    String usernaeme = jNameAdmin.getText();
                    
                    AdminUserAdd obj = new AdminUserAdd();
                    obj.deleteUser(usernaeme);
          }//GEN-LAST:event_jDeleteButttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddEditUSers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddEditUSers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddEditUSers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddEditUSers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddEditUsers().setVisible(true);
            }
        });
    }

          // Variables declaration - do not modify//GEN-BEGIN:variables
          private javax.swing.JButton jAddButton;
          private javax.swing.JButton jButton1;
          private javax.swing.JPasswordField jConfirmPassAdmin;
          private javax.swing.JButton jDeleteButtton;
          private javax.swing.JLabel jLabel1;
          private javax.swing.JLabel jLabel2;
          private javax.swing.JLabel jLabel3;
          private javax.swing.JLabel jLabel4;
          private javax.swing.JLabel jLabel5;
          private javax.swing.JLabel jLabel6;
          private javax.swing.JTextField jNameAdmin;
          private javax.swing.JPasswordField jPasswordAdmin;
          private javax.swing.JComboBox<String> jTypeAdmin;
          private javax.swing.JButton jUpdateButton;
          // End of variables declaration//GEN-END:variables
}
