package Admin;


import classes.DataBaseConnection;
import classes.Resource;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Asus
 */
public class Resources extends javax.swing.JFrame {

    /**
     * Creates new form UserSettings
     */
    public Resources() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableResorce = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(450, 650));
        setResizable(false);
        setSize(new java.awt.Dimension(450, 650));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Classroom");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 150, -1));

        jComboBox1.setBackground(new java.awt.Color(38, 106, 169));
        jComboBox1.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cls1", "cls2", "cls3", "cls4", "cls5" }));
        jComboBox1.setBorder(null);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 170, 30));

        jTableResorce.setBackground(new java.awt.Color(38, 106, 169));
        jTableResorce.setFont(new java.awt.Font("Poppins Medium", 0, 18)); // NOI18N
        jTableResorce.setForeground(new java.awt.Color(255, 255, 255));
        jTableResorce.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Type", "Quantity"
            }
        ));
        jTableResorce.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTableResorce.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableResorce.setGridColor(new java.awt.Color(255, 255, 255));
        jTableResorce.setRowHeight(25);
        jTableResorce.setRowMargin(5);
        jTableResorce.setRowSelectionAllowed(false);
        jTableResorce.setSelectionBackground(new java.awt.Color(38, 106, 169));
        jTableResorce.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jTableResorce.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        jTableResorce.setShowGrid(false);
        jScrollPane1.setViewportView(jTableResorce);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 350, 340));

        jButton4.setBackground(new java.awt.Color(38, 106, 169));
        jButton4.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Add Resources");
        jButton4.setAlignmentY(0.0F);
        jButton4.setBorder(null);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 170, 40));

        jButton3.setBackground(new java.awt.Color(38, 106, 169));
        jButton3.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/refresh-page-option.png"))); // NOI18N
        jButton3.setText("Refresh");
        jButton3.setAlignmentY(0.0F);
        jButton3.setBorder(null);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton3.setIconTextGap(7);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 160, 40));

        jButton1.setBackground(new java.awt.Color(237, 30, 121));
        jButton1.setFont(new java.awt.Font("Poppins Medium", 0, 15)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/back.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.setAlignmentY(0.0F);
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 80, 40));

        jLabel2.setBackground(new java.awt.Color(237, 30, 121));
        jLabel2.setFont(new java.awt.Font("Poppins Medium", 0, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Resources");
        jLabel2.setAlignmentY(0.0F);
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 230, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg-08.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 490, 670));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.toBack();
        setVisible(false);
        new Dashboard().toFront();
        new Dashboard().setState(java.awt.Frame.NORMAL);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //close();
        AddEditResources add = new AddEditResources();
        add.setVisible (true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        
        String class_selected = jComboBox1.getSelectedItem().toString();
        
        Resource obj = new Resource();
        
        obj.showResource(class_selected);
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        showResource();
        
    }//GEN-LAST:event_jButton3ActionPerformed

    
    public void showResource(){
        
        try {
            
            ResultSet rs;
            
            Connection con = DataBaseConnection.getCon();
            Statement st = con.createStatement();
            
            
            if ( jComboBox1.getSelectedItem().toString() == "cls1" ){
                
                String sql = "SELECT type, quantity FROM resources WHERE classroom = 'cls1'";
                rs = st.executeQuery(sql);
                
            } else if ( jComboBox1.getSelectedItem().toString() == "cls2" ){
                
                String sql = "SELECT type, quantity FROM resources WHERE classroom = 'cls2'";
                rs = st.executeQuery(sql);
                
            } else if ( jComboBox1.getSelectedItem().toString() == "cls3" ){
                
                String sql = "SELECT type, quantity FROM resources WHERE classroom = 'cls3'";
                rs = st.executeQuery(sql);
                
            } else if ( jComboBox1.getSelectedItem().toString() == "cls4" ){
                
                String sql = "SELECT type, quantity FROM resources WHERE classroom = 'cls4'";
                rs = st.executeQuery(sql);
                
            } else {
                
                String sql = "SELECT type, quantity FROM resources WHERE classroom = 'cls5'";
                rs = st.executeQuery(sql);
                
            }
            
            
            DefaultTableModel tableModel = new DefaultTableModel();
            jTableResorce.setModel(tableModel);
            
            
            tableModel.setColumnIdentifiers(new Object[] {"Type", "Quantity"});
            
            while (rs.next()) {
            Object[] row = new Object[2];
            row[0] = rs.getString("type");
            row[1] = rs.getInt("quantity");
            } 
            
            
        } catch (SQLException ex) {
            System.out.println("Database connection failed");
        }
        
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Resources.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Resources.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Resources.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Resources.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Resources().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    public javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTableResorce;
    // End of variables declaration//GEN-END:variables
}
