
import classes.LoginValid;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Muhammed
 */
public class Login extends javax.swing.JFrame {
          
          //varible for email
          public String username_entered;
          
          //variable for password
          public String password_entered;
          
          //variable for role
          //public String role_entered;

    
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
          // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
          private void initComponents() {

                    jLoginButton = new javax.swing.JButton();
                    jComboBox1 = new javax.swing.JComboBox<>();
                    jPasswordField1 = new javax.swing.JPasswordField();
                    jUserNameField = new javax.swing.JTextField();
                    jLabel4 = new javax.swing.JLabel();
                    jLabel3 = new javax.swing.JLabel();
                    jLabel2 = new javax.swing.JLabel();
                    jLabel5 = new javax.swing.JLabel();

                    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                    setBackground(new java.awt.Color(255, 255, 255));
                    setResizable(false);
                    setSize(new java.awt.Dimension(750, 500));
                    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                    jLoginButton.setBackground(new java.awt.Color(237, 30, 121));
                    jLoginButton.setFont(new java.awt.Font("Poppins Light", 1, 18)); // NOI18N
                    jLoginButton.setForeground(new java.awt.Color(255, 255, 255));
                    jLoginButton.setText("Submit");
                    jLoginButton.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        jLoginButtonActionPerformed(evt);
                              }
                    });
                    getContentPane().add(jLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, 120, 40));

                    jComboBox1.setBackground(new java.awt.Color(64, 134, 200));
                    jComboBox1.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
                    jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
                    jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Lecture", "Student" }));
                    jComboBox1.setToolTipText("");
                    jComboBox1.setBorder(null);
                    jComboBox1.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        jComboBox1ActionPerformed(evt);
                              }
                    });
                    getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, 170, 40));

                    jPasswordField1.setBackground(new java.awt.Color(64, 134, 200));
                    jPasswordField1.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
                    jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
                    jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                    jPasswordField1.setActionCommand("<Not Set>");
                    jPasswordField1.setBorder(null);
                    jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        jPasswordField1ActionPerformed(evt);
                              }
                    });
                    getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 170, 40));

                    jUserNameField.setBackground(new java.awt.Color(64, 134, 200));
                    jUserNameField.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
                    jUserNameField.setForeground(new java.awt.Color(255, 255, 255));
                    jUserNameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                    jUserNameField.setBorder(null);
                    jUserNameField.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        jUserNameFieldActionPerformed(evt);
                              }
                    });
                    getContentPane().add(jUserNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 170, 40));

                    jLabel4.setBackground(new java.awt.Color(255, 255, 255));
                    jLabel4.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
                    jLabel4.setForeground(new java.awt.Color(64, 134, 200));
                    jLabel4.setText("Role");
                    getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 230, 110, 60));

                    jLabel3.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
                    jLabel3.setForeground(new java.awt.Color(64, 134, 200));
                    jLabel3.setText("Password");
                    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 110, 60));

                    jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
                    jLabel2.setForeground(new java.awt.Color(64, 134, 200));
                    jLabel2.setText("User Name");
                    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 110, 60));

                    jLabel5.setBackground(new java.awt.Color(255, 255, 255));
                    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/login-04.png"))); // NOI18N
                    jLabel5.setOpaque(true);
                    getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -10, -1, -1));

                    setSize(new java.awt.Dimension(779, 525));
                    setLocationRelativeTo(null);
          }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
                    // TODO add your handling code here:
                   
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLoginButtonActionPerformed
        // TODO add your handling code here:
        // get the user entered inputs
        String username =  jUserNameField.getText();
        String password = jPasswordField1.getText();
        
        // creatind the object of UaerValid
        LoginValid obj = new LoginValid();
        
        // validating the ebntered username and password
        boolean valid_login = obj.loginValidation(username, password);
        
        // if the username and password are correct proceed to the home page
        if ( valid_login ){
                  Dashboard objDash = new Dashboard();
                  objDash.setVisible(true);
                  System.out.println("Login Successfull");
        }
        else {
                  // incorrect inputs display a message
                  JOptionPane.showMessageDialog(null, "Invalid username or password");
        }
    }//GEN-LAST:event_jLoginButtonActionPerformed

          private void jUserNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jUserNameFieldActionPerformed
                    // TODO add your handling code here: 
          }//GEN-LAST:event_jUserNameFieldActionPerformed

          private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
                    // TODO add your handling code here:
          }//GEN-LAST:event_jPasswordField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

          // Variables declaration - do not modify//GEN-BEGIN:variables
          private javax.swing.JComboBox<String> jComboBox1;
          private javax.swing.JLabel jLabel2;
          private javax.swing.JLabel jLabel3;
          private javax.swing.JLabel jLabel4;
          private javax.swing.JLabel jLabel5;
          private javax.swing.JButton jLoginButton;
          private javax.swing.JPasswordField jPasswordField1;
          private javax.swing.JTextField jUserNameField;
          // End of variables declaration//GEN-END:variables
}
