
import Admin.Dashboard;
import classes.LoginValidate;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import javax.swing.JOptionPane;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Asus
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
          // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
          private void initComponents() {

                    jButton1 = new javax.swing.JButton();
                    jPasswordField1 = new javax.swing.JPasswordField();
                    jUserName = new javax.swing.JTextField();
                    jLabel3 = new javax.swing.JLabel();
                    jLabel2 = new javax.swing.JLabel();
                    jLabel5 = new javax.swing.JLabel();

                    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                    setBackground(new java.awt.Color(255, 255, 255));
                    setResizable(false);
                    setSize(new java.awt.Dimension(750, 500));
                    getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                    jButton1.setBackground(new java.awt.Color(237, 30, 121));
                    jButton1.setFont(new java.awt.Font("Poppins Light", 1, 18)); // NOI18N
                    jButton1.setForeground(new java.awt.Color(255, 255, 255));
                    jButton1.setText("Login");
                    jButton1.addActionListener(new java.awt.event.ActionListener() {
                              public void actionPerformed(java.awt.event.ActionEvent evt) {
                                        jButton1ActionPerformed(evt);
                              }
                    });
                    getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 120, 40));

                    jPasswordField1.setBackground(new java.awt.Color(145, 184, 227));
                    jPasswordField1.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
                    jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
                    jPasswordField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                    jPasswordField1.setActionCommand("<Not Set>");
                    jPasswordField1.setBorder(null);
                    getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 170, 40));

                    jUserName.setBackground(new java.awt.Color(145, 184, 227));
                    jUserName.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
                    jUserName.setForeground(new java.awt.Color(255, 255, 255));
                    jUserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
                    jUserName.setBorder(null);
                    getContentPane().add(jUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 170, 40));

                    jLabel3.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
                    jLabel3.setForeground(new java.awt.Color(255, 255, 255));
                    jLabel3.setText("Password");
                    getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 110, 60));

                    jLabel2.setFont(new java.awt.Font("Poppins SemiBold", 0, 20)); // NOI18N
                    jLabel2.setForeground(new java.awt.Color(255, 255, 255));
                    jLabel2.setText("Username");
                    getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 110, 60));

                    jLabel5.setBackground(new java.awt.Color(64, 134, 200));
                    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login-04.png"))); // NOI18N
                    jLabel5.setOpaque(true);
                    getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(-40, -10, -1, -1));

                    setSize(new java.awt.Dimension(779, 525));
                    setLocationRelativeTo(null);
          }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        // written by : Muhammed
        // username
        String username = jUserName.getText();
        // password
        String password = jPasswordField1.getText();
        
        LoginValidate obj = new LoginValidate();
        
        boolean isValidLogin = obj.loginValidation(username, password);
        if (isValidLogin) {
                  // login successful, open main application window
                  Dashboard dash = new Dashboard();
                  dash.setVisible(true);
                  dispose(); // close the login window
        } else {
                  // login failed, display error message
                  JOptionPane.showMessageDialog(this, "Invalid username or password. Please try again.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

          // Variables declaration - do not modify//GEN-BEGIN:variables
          private javax.swing.JButton jButton1;
          private javax.swing.JLabel jLabel2;
          private javax.swing.JLabel jLabel3;
          private javax.swing.JLabel jLabel5;
          private javax.swing.JPasswordField jPasswordField1;
          private javax.swing.JTextField jUserName;
          // End of variables declaration//GEN-END:variables
}
